apiVersion: apps/v1
kind: Deployment
metadata:
  name: codito-microservices-orders
  labels:
    app: codito
    microservice: orders
spec:
  selector:
    matchLabels:
      app: codito
      microservice: orders
  template:
    metadata:
      labels:
        app: codito
        microservice: orders
    spec:
      containers:
      - name: orders-api
        image: coditeu/microservices-with-api-management-services-order
        ports:
        - containerPort: 80
        env:
        - name: AZURESTORAGE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: orders-secrets
             key: AZURESTORAGE_CONNECTIONSTRING
        - name: SHIPMENTS_API_URI
          value: http://codito-microservices-shipments-internal-service.webinar-sandbox:88/api/v1/shipments
        livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
        readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: codito-microservices-orders-loadbalancer-service
  labels:
    app: codito
    microservice: orders
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8889
      targetPort: 80
      protocol: TCP
  selector:
    app: codito
    microservice: orders
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  labels:
    app: codito
    microservice: orders
data:
  AZURESTORAGE_CONNECTIONSTRING: <base64 encoded connection string>