resources:
- repo: self
trigger: none
pr: none
variables:
  DotNet.SDK.Version: '2.2.300'
  Images.Orders.Name: 'coditeu/microservices-with-api-management-services-order'
stages:
- stage: 'Order Service'
  displayName: 'Build and Push Order Docker image'
  jobs:
   - job: Build
     pool:
       vmImage: ubuntu-16.04
     steps:
     - task: DotNetCoreInstaller@0
       displayName: 'Install .NET SDK'
       inputs:
        version: '$(DotNet.SDK.Version)'
     - task: Docker@1
       displayName: 'Build Docker image'
       inputs:
        dockerFile: ./src/microservices/Demo.Microservices.Orders.API/Dockerfile
        imageName: '$(Images.Orders.Name)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: ./src/
     - task: Docker@1
       displayName: 'Push ''latest'' to Docker Hub'
       inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(Images.Orders.Name):latest'
