version: '3.4'

services:
  demo.microservices.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SHIPMENTS_API_URI=http://demo.microservices.shipments.api/api/v1/shipments
      - AZURESTORAGE_CONNECTIONSTRING=DefaultEndpointsProtocol=https;AccountName=codito;AccountKey=2Ga0Y/as4QBr+7N3Ej7cnfK397uKT1fglypXACHM4o4xlkVVh56SNGKjVMqZfl9WQebkeWC511UWBrX4TQQYqg==;EndpointSuffix=core.windows.net
    ports:
      - "80"

  demo.microservices.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURESTORAGE_CONNECTIONSTRING=DefaultEndpointsProtocol=https;AccountName=codito;AccountKey=2Ga0Y/as4QBr+7N3Ej7cnfK397uKT1fglypXACHM4o4xlkVVh56SNGKjVMqZfl9WQebkeWC511UWBrX4TQQYqg==;EndpointSuffix=core.windows.net
    ports:
      - "80"

  demo.microservices.shipments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURESTORAGE_CONNECTIONSTRING=DefaultEndpointsProtocol=https;AccountName=codito;AccountKey=2Ga0Y/as4QBr+7N3Ej7cnfK397uKT1fglypXACHM4o4xlkVVh56SNGKjVMqZfl9WQebkeWC511UWBrX4TQQYqg==;EndpointSuffix=core.windows.net
    ports:
      - "80"

  demo.microservices.api.docs:
    ports:
      - "889:80"

  demo.microservices.gateway:
    env_file:
      - api-gateway.conf
    ports:
      - "888:8080"