version: '3.4'

services:
  demo.microservices.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SHIPMENTS_API_URI=http://demo.microservices.shipments.api/api/v1/shipments
      - AZURESTORAGE_CONNECTIONSTRING=
    ports:
      - "80"

  demo.microservices.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURESTORAGE_CONNECTIONSTRING=
    ports:
      - "80"

  demo.microservices.shipments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURESTORAGE_CONNECTIONSTRING=
    ports:
      - "80"