apiVersion: apps/v1
kind: Deployment
metadata:
  name: codito-microservices-products
  labels:
    app: codito
    microservice: products
spec:
  selector:
    matchLabels:
      app: codito
      microservice: products
  template:
    metadata:
      labels:
        app: codito
        microservice: products
    spec:
      containers:
      - name: products-api
        image: ghcr.io/coditeu/microservices-with-api-management-services-product:latest
        ports:
        - containerPort: 80
        env:
        - name: AZURESTORAGE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: products-secrets
             key: AZURESTORAGE_CONNECTIONSTRING
        livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
        readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: codito-microservices-products-loadbalancer-service
  labels:
    app: codito
    microservice: products
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: codito-kubernetes-products
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8888
      targetPort: 80
      protocol: TCP
  selector:
    app: codito
    microservice: products
---
apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
  labels:
    app: codito
    microservice: products
data:
  AZURESTORAGE_CONNECTIONSTRING: <base64 encoded connection string>